/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class signUP extends javax.swing.JFrame {

    /**
     * Creates new form signUP
     */
    public signUP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fl5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fl1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        fl2 = new javax.swing.JTextField();
        fl3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fl4 = new javax.swing.JTextField();
        Signin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(242, 226, 210));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel4.setText("Nom complet");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        fl5.setBackground(new java.awt.Color(242, 226, 210));
        fl5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fl5ActionPerformed(evt);
            }
        });
        jPanel1.add(fl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 260, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        fl1.setBackground(new java.awt.Color(242, 226, 210));
        fl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fl1ActionPerformed(evt);
            }
        });
        jPanel1.add(fl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 260, 30));

        jButton1.setBackground(new java.awt.Color(204, 142, 104));
        jButton1.setFont(new java.awt.Font("Brush Script MT", 1, 18)); // NOI18N
        jButton1.setText("LOGIN IN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 190, 30));

        jButton2.setBackground(new java.awt.Color(204, 142, 104));
        jButton2.setFont(new java.awt.Font("Brush Script MT", 1, 18)); // NOI18N
        jButton2.setText("SIGN IN");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 142, 104));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 110, 10));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel7.setText("Telephone");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        fl2.setBackground(new java.awt.Color(242, 226, 210));
        fl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fl2ActionPerformed(evt);
            }
        });
        jPanel1.add(fl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 260, 30));

        fl3.setBackground(new java.awt.Color(242, 226, 210));
        fl3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fl3ActionPerformed(evt);
            }
        });
        jPanel1.add(fl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 260, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel8.setText("CIN");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 30, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel9.setText("Email");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        fl4.setBackground(new java.awt.Color(242, 226, 210));
        fl4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fl4ActionPerformed(evt);
            }
        });
        jPanel1.add(fl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 260, 30));

        Signin.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
        Signin.setText("Sign up ");
        jPanel1.add(Signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 130, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mariage (1).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 320, 480));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Adobe Express - file (4).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 542, 504));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fl5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fl5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fl5ActionPerformed

    private void fl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fl1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String v1= fl1.getText();
          String v2= fl2.getText();
          String v3= fl3.getText();
          String v4= fl4.getText();
          String v5= fl5.getText();
         
        try{
         if(v1.isEmpty()|| v2.isEmpty() || v3.isEmpty()|| v4.isEmpty() || v5.isEmpty()){
              JOptionPane.showMessageDialog(null,"Full in the fields please !!");
   
         }
            
         else {
           
           Class.forName("com.mysql.jdbc.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/projet_java","root","");
        String req = "INSERT INTO signupp(nomPrenom, telephone, cin, email, password) VALUES (?, ?, ?, ?, ?)";
        
          PreparedStatement p = con.prepareStatement(req);
                 p.setString(1, v1); // nomPrenom
                 p.setString(2, v2); // telephone
                 p.setString(3, v3); // cin
                 p.setString(4, v4); // email
                 p.setString(5, v5); // password
                 p.executeUpdate();
                   JOptionPane.showMessageDialog(null,"Your data is save ");
        
        main frame2 = new main();
                frame2.setVisible(true);

                // Fermeture de la première frame 
                dispose();
         }}
       catch(Exception e){
           e.printStackTrace();
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fl2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fl2ActionPerformed

    private void fl3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fl3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fl3ActionPerformed

    private void fl4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fl4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fl4ActionPerformed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
          SIGN DeuxiemmeFrame = new SIGN();
            DeuxiemmeFrame.setVisible(true);

            // Close the current frame
            dispose();
        
    }//GEN-LAST:event_jButton2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Signin;
    private javax.swing.JTextField fl1;
    private javax.swing.JTextField fl2;
    private javax.swing.JTextField fl3;
    private javax.swing.JTextField fl4;
    private javax.swing.JTextField fl5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
